# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=picmid -start-before=instruction-select -verify-machineinstrs -o - %s | FileCheck %s

# CHECK:              .globl  add_imm                         ; -- Begin function add_imm
# CHECK-NEXT:         .type   add_imm,@function
# CHECK-NEXT: add_imm:                                ; @add_imm
# CHECK-NEXT: ; %bb.0:                                ; %entry
# CHECK-NEXT:         movwf   120
# CHECK-NEXT:         movf    112,0
# CHECK-NEXT:         movwf   113
# CHECK-NEXT:         movf    120,0
# CHECK-NEXT:         addwf   113,1
# CHECK-NEXT:         movf    113,0
# CHECK-NEXT:         addwf   112,1
# CHECK-NEXT:         return
# CHECK-NEXT: .Lfunc_end0:
# CHECK-NEXT:         .size   add_imm, .Lfunc_end0-add_imm
# CHECK-NEXT:                                         ; -- End function
# CHECK-NEXT:         .section        ".note.GNU-stack","",@progbits

---
name: add_imm
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $w, $r0, $r1, $r8
    %0:any(s8) = COPY $w
    %1:any(s8) = COPY $r0
    %2:any(s8) = G_ADD %0, %1
    %3:any(s8) = G_ADD %2, %1
    G_RETURN implicit %3
