# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=picmid -run-pass=instruction-select -verify-machineinstrs -o - %s | FileCheck %s

---
name: add_imm
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: add_imm
    ; CHECK: [[COPY:%[0-9]+]]:wc = COPY $w
    ; CHECK-NEXT: [[ADDLW:%[0-9]+]]:wc = G_ADDLW [[COPY]], 42
    ; CHECK-NEXT: G_RETURN implicit [[ADDLW]]
    %0:any(s8) = COPY $w
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s8) = G_ADD %0, %1
    G_RETURN implicit %2
---
name: add_f
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: add_f
    ; CHECK: [[COPY:%[0-9]+]]:wc = COPY $w
    ; CHECK-NEXT: [[R0:%[0-9]+]]:imag = COPY $r0
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:imag = G_ADDWF_F [[COPY]], [[R0]]
    ; CHECK-NEXT: G_RETURN implicit [[ADD]]
    %0:any(s8) = COPY $w
    %1:any(s8) = COPY $r0
    %2:any(s8) = G_ADD %0, %1
    G_RETURN implicit %2
---
name: add_w
legalized: true
regBankSelected: true
body: |
  ; TODO: Fix this! Should not happen.
  ; CHECK-LABEL: name: add_w
  ; CHECK: [[COPY:%[0-9]+]]:wc = COPY $w
  ; CHECK-NEXT: [[R0:%[0-9]+]]:imag = COPY $r0
  ; CHECK-NEXT: [[ADD:%[0-9]+]]:imag = G_ADDWF_F [[COPY]], [[R0]]
  ; CHECK-NEXT: [[W:%[0-9]+]]:wc = COPY [[ADD]]
  ; CHECK-NEXT: [[ADD1:%[0-9]+]]:imag = G_ADDWF_F [[W]], [[R0]] 
  ; CHECK-NEXT: G_RETURN implicit [[ADD1]]
  bb.0.entry:
    %0:any(s8) = COPY $w
    %1:any(s8) = COPY $r0
    %2:any(s8) = G_ADD %0, %1
    %3:any(s8) = G_ADD %2, %1
    G_RETURN implicit %3
---
name: sub_imm
legalized: true
regBankSelected: true
body: |
  ; CHECK-LABEL: name: sub_imm
  ; CHECK: [[W:%[0-9]+]]:wc = COPY $w
  ; CHECK-NEXT: [[SUB:%[0-9]+]]:wc = G_SUBLW [[W]], 42
  ; CHECK-NEXT: G_RETURN implicit [[SUB]]
  bb.0.entry:
    %0:any(s8) = COPY $w
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s8) = G_SUB %1, %0
    G_RETURN implicit %2
---
name: sub_f
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: sub_f
    ; CHECK: [[W:%[0-9]+]]:wc = COPY $w
    ; CHECK-NEXT: [[R0:%[0-9]+]]:imag = COPY $r0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:imag = G_SUBWF_F [[W]], [[R0]]
    ; CHECK-NEXT: G_RETURN implicit [[SUB]]
    %0:any(s8) = COPY $w
    %1:any(s8) = COPY $r0
    %2:any(s8) = G_SUB %1, %0
    G_RETURN implicit %2
---
name: decf_f
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: decf_f
    ; CHECK: [[R0:%[0-9]+]]:imag = COPY $r0
    ; CHECK-NEXT: [[DECF:%[0-9]+]]:imag = G_DECF_F [[R0]]
    ; CHECK-NEXT: G_RETURN implicit [[DECF]]
    %0:any(s8) = COPY $r0
    %1:any(s8) = G_CONSTANT i8 1
    %2:any(s8) = G_SUB %0, %1
    G_RETURN implicit %2
---
name: incf_f
legalized: true
regBankSelected: true
body: |
  bb.0.entry:
    ; CHECK-LABEL: name: incf_f
    ; CHECK: [[R0:%[0-9]+]]:imag = COPY $r0
    ; CHECK-NEXT: [[INCF:%[0-9]+]]:imag = G_INCF_F [[R0]]
    ; CHECK-NEXT: G_RETURN implicit [[INCF]]
    %0:any(s8) = COPY $r0
    %1:any(s8) = G_CONSTANT i8 1
    %2:any(s8) = G_ADD %0, %1
    G_RETURN implicit %2
