# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=picmid -start-before=instruction-select -verify-machineinstrs -o - %s | FileCheck %s

# CHECK:              .globl  add_imm                         ; -- Begin function add_imm
# CHECK-NEXT:         .type   add_imm,@function
# CHECK-NEXT: add_imm:                                ; @add_imm
# CHECK-NEXT: ; %bb.0:                                ; %entry
# CHECK-NEXT:         addlw   42
# CHECK-NEXT:         sublw   42
# CHECK-NEXT:         return
# CHECK-NEXT: .Lfunc_end0:
# CHECK-NEXT:         .size   add_imm, .Lfunc_end0-add_imm
# CHECK-NEXT:                                         ; -- End function
# CHECK-NEXT:         .section        ".note.GNU-stack","",@progbits

---
name: add_imm
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $w
    %0:any(s8) = COPY $w
    %1:any(s8) = G_CONSTANT i8 42
    %2:any(s8) = G_ADD %0, %1
    %3:any(s8) = G_SUB %1, %2
    G_RETURN implicit %3
