# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=picmid -start-before=instruction-select -verify-machineinstrs -o - %s | FileCheck %s

# CHECK:              .text
# CHECK-NEXT:         .file   "instruction-selector-to-mc-call.mir"
# CHECK-NEXT:         .globl  caller                          ; -- Begin function caller
# CHECK-NEXT:         .type   caller,@function
# CHECK-NEXT: caller:                                 ; @caller
# CHECK-NEXT: ; %bb.0:                                ; %entry
# CHECK-NEXT:         call    callee
# CHECK-NEXT: .Lfunc_end0:
# CHECK-NEXT:         .size   caller, .Lfunc_end0-caller
# CHECK-NEXT:                                         ; -- End function
# CHECK-NEXT:         .globl  callee                          ; -- Begin function callee
# CHECK-NEXT:         .type   callee,@function
# CHECK-NEXT: callee:                                 ; @callee
# CHECK-NEXT: ; %bb.0:                                ; %entry
# CHECK-NEXT:         addlw   69
# CHECK-NEXT:         return
# CHECK-NEXT: .Lfunc_end1:
# CHECK-NEXT:         .size   callee, .Lfunc_end1-callee
# CHECK-NEXT:                                         ; -- End function
# CHECK-NEXT:         .section        ".note.GNU-stack","",@progbits

---
name: caller
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0.entry:
    G_CALL &callee

---
name: callee
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $w
    %0:any(s8) = COPY $w
    %2:any(s8) = G_CONSTANT i8 69
    %1:any(s8) = G_ADD %0, %2
    G_RETURN implicit %1
